
- name: Disable Default Nginx module
  ansible.builtin.shell: dnf module disable nginx -y

- name: Enable Nginx 24 version
  ansible.builtin.shell: dnf module enable nginx:1.24 -y

- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: Copy Nginx config file
  ansible.builtin.copy:
    src: nginx.conf
    det: /etc/nginx/nginx.conf

- name: Start nginx
  ansible.builtin.systemd_service:
    state: restarted
    name: nginx
    enabled: true